language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: U7Ywsue16jB8753IncZfOZjf1xRi2byNGlbqI0OfidsRtLm3o3LQ5p9LqMT82u1auDFi7fGa8nIHteTkJ4HirFBTfukIlUDXQUKvLqhlZ5VBaBtk55yzF/FYf1qJi03jD8Bm/rNNvp9VCKcCXZnDQEHwwvSbOieQLvTT44ZpTBANlHbYdEGobKG1V3sVMyr5HfP+xUa1mQIfGUWezT0vPe1Tt0vl3j4Kf1ZXv3MmksVHz1LMkwX0urDK/0u+NU2ZwiJt5AxMoZ3OsJ0tiSXAg2dMoA0y4n2390c7Crn0ki2Y1nTre1g2OMmr8lg4741ga3r2pIlNjZ58/26dSZHKevVKcz8kSIUh4C1urb1Cok1b/6fGB/VUK0sGaSluj8QmjlEFyzQVoodoPIERdB1j/BwVOZdqq8I17PpymTN0AvsjA65TvmEVXCIgXWB1nsHswOT4q7uq/BpmHT3d3yXjaJC4Enj1x7XhFkmJ92fXn3ubLWxCS5/4MecPzksNg4xvXXGMML6jRXD7q5ayWmBhbihot9PAwXmckHb+RbjTzulF5oloq1SouCWh96Wsd2iZCa7cKpzcoGgaiQJlSkNgIVrMlBv3TySdlZhCDzwYdpF9raZ238GJFQDtFvX5ZhUTr7+wIWoToz6KAZsEETjL5npDbILA8J4xIfzpa9P8KxQ=
    on_pull_requests: false
    on_failure: never
install:
- npm install
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm prune
- greenkeeper-lockfile-update
after_success:
- npm run coveralls
- npm run semantic-release
after_script:
- greenkeeper-lockfile-upload
